import { Toaster } from "@/components/ui/sonner";
import { TRPCProvider } from "@/trpc/client";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Load the Inter font with the Latin character subset
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the application (used by Next.js for SEO)
export const metadata: Metadata = {
  title: "Create Next App", // Default title for the application
  description: "Generated by create next app", // Description meta tag
};

// Root layout component that wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Type definition for children (React nodes)
}>) {
  return (
    // Wrap the entire application with ClerkProvider for authentication
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={`${inter.className}`}>
          {/* Provide API access via tRPC */}
          <TRPCProvider>
            {/* Display toast notifications globally */}
            <Toaster />
            {/* Render child components (i.e., pages and layouts) */}
            {children}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
